apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: teamops
  labels:
    app: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: teamops-api:latest
          imagePullPolicy: Never
          command: ["celery", "-A", "teamops", "worker", "--loglevel=INFO"]
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "800m"
              memory: "1Gi"
