apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: teamops
type: Opaque
stringData:
  POSTGRES_DB: "teamops_db"
  POSTGRES_USER: "teamops_user"
  POSTGRES_PASSWORD: "teamops_pass"
