# Generated by Django 6.0 on 2025-12-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PM', 'Project Manager'), ('DEV', 'Developer')], default='DEV', max_length=10),
        ),
    ]
