# Generated by Django 6.0.1 on 2026-02-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_invited_at_user_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_token_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
